ci: edit message vie telegram

diff --git a/.github/workflows/ci-test.yml b/.github/workflows/ci-test.yml
--- a/.github/workflows/ci-test.yml
+++ b/.github/workflows/ci-test.yml
@@ -46,7 +46,7 @@ jobs:
 
       - name: Run Snyk scan
         run: |
-          docker run --rm \
+          if ! docker run --rm \
             --entrypoint /bin/sh \
             -e SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} \
             -v $(pwd):/app -w /app \
@@ -55,9 +55,11 @@ jobs:
               snyk code test --severity-threshold=high --json > snyk_sast_result.json
               SNYK_EXIT_CODE=\$?
               npm install -g snyk-to-html
-              snyk-to-html -i snyk_sast_result.json -o ${{ env.SNYKSCAN_SAST_REPORT }}.html || true
+              snyk-to-html -i snyk_sast_result.json -o ${{ env.SNYKSCAN_SAST_REPORT }}.html || true; then
+              echo "::error title=Snyk SAST Scan Failed:: Found issues with 'HIGH/CRITICAL' severity"
               exit \$SNYK_EXIT_CODE
             "
+          fi
 
       - name: Upload Reports
         uses: actions/upload-artifact@v4
@@ -85,7 +87,7 @@ jobs:
       - name: Run Snyk scan
         continue-on-error: true
         run: |
-          docker run --rm \
+          if ! docker run --rm \
             --entrypoint /bin/sh \
             -e SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} \
             -v $(pwd):/app -w /app \
@@ -94,9 +96,11 @@ jobs:
               snyk test --severity-threshold=high --all-projects --json > snyk_sca_result.json
               SNYK_EXIT_CODE=\$?
               npm install -g snyk-to-html
-              snyk-to-html -i snyk_sca_result.json -o ${{ env.SNYKSCAN_SCA_REPORT }}.html || true
+              snyk-to-html -i snyk_sca_result.json -o ${{ env.SNYKSCAN_SCA_REPORT }}.html || true; then
+              echo "::error title=Snyk SCA Scan Failed:: Found issues with 'HIGH/CRITICAL' severity"
               exit \$SNYK_EXIT_CODE
             "
+          fi
 
       - name: Upload Reports
         uses: actions/upload-artifact@v4
@@ -139,8 +143,7 @@ jobs:
   notify-request-approval:
     name: Send Approval Request to Telegram
     runs-on: ubuntu-latest
-   
-    needs: [snyk-sast, snyk-sca, trivy-fs-scan]
+
     steps:
       - name: Send Notification
         uses: appleboy/telegram-action@master
@@ -149,18 +152,18 @@ jobs:
           token: ${{ secrets.TELEGRAM_TOKEN }}
           message: |
             [WAITING APPROVAL] 
-            Tất cả các bước quét bảo mật mã nguồn đã thành công (PASSED)!
-            Hệ thống đang chờ bạn phê duyệt để tiến hành build và đẩy image lên ECR.
+            All source code security scans have PASSED!
+            The pipeline is now waiting for your approval to build and push the image to ECR.
             
-            Người kích hoạt: ${{ github.actor }}
-            Nhánh: ${{ github.ref_name }}
-            Bấm vào đây để Phê Duyệt: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/approval-request
+            Triggered by: ${{ github.actor }}
+            Branch: ${{ github.ref_name }}
+            Click here to Approve: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
   build:
     name: Build and Push ECR
     runs-on: ubuntu-latest
     environment: testing
-    needs: [snyk-sast, snyk-sca, trivy-fs-scan, notify-request-approval]
+    needs: notify-request-approval
 
     steps:
       - name: Checkout code
